server.port=7118
spring.application.name=http-client-module

#RedisCluster
redis.cluster.nodes=localhost:6379
redis.threadPool.maxTotal=60
redis.threadPool.maxIdle=50
redis.threadPool.minIdle=10
redis.threadPool.blockWhenExhausted=true
redis.connection.timeout=2000
redis.so.timeout=2000
redis.maxAttempts=20
redis.connection.user=
redis.connection.password=
redis.standalone.enabled=true
proxy.mode.responseTimeout=5000

#Websocket
websocket.server.enabled=true
websocket.server.host=localhost
websocket.server.port=8080
websocket.server.path=/ws
websocket.header.name=Authorization
websocket.header.value=fcb13146-ecd7-46a5-b9cb-a1e75fae9bdc
websocket.retry.intervalSeconds=10

# HTTP2
application.useHttp2=true

# Default data coding scheme for SMSC-generated DLRs (0=GSM7)
smsc.default.dlr.data-coding=0

#VirtualThread
spring.threads.virtual.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.concurrency=1
spring.kafka.consumer.reconnect.backoff.ms=1000
spring.kafka.consumer.reconnect.backoff.max.ms=10000
spring.kafka.consumer.session.timeout.ms=30000
spring.kafka.consumer.heartbeat.interval.ms=10000
spring.kafka.producer.reconnect.backoff.ms=1000
spring.kafka.producer.reconnect.backoff.max.ms=10000

# Scylla
scylla.contact.points=localhost:9042
scylla.datacenter=datacenter1
scylla.user=
scylla.password=